name: Check

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pandoc/actions/setup@v1
      - name: Setup zh_CN.UTF-8 locale
        run: |
          sudo locale-gen zh_CN.UTF-8
          locale --all-locales
      - uses: astral-sh/setup-uv@v7
      - run: |
          uv sync --locked

      - name: Run tests
        run: |
          uv run --frozen tests/run_tests.py

      - name: Build CSL styles
        run: |
          CSL_BACKTRACE=1 uv run --frozen csl-sanitizer
      - uses: actions/upload-artifact@v6
        with:
          path: ./dist/
