name: Check

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: pandoc/actions/setup@v1
      - name: Setup hayagriva
        shell: bash
        run: |
          set -euxo pipefail

          curl -LO https://github.com/typst-community/dev-builds/releases/download/hayagriva-v0.9.1/hayagriva-x86_64-unknown-linux-musl.tar.xz
          tar -xf hayagriva-x86_64-unknown-linux-musl.tar.xz
          mkdir -p ~/.local/bin/
          mv ./hayagriva-x86_64-unknown-linux-musl/hayagriva ~/.local/bin/
      - name: Setup zh_CN.UTF-8 locale
        run: |
          sudo locale-gen zh_CN.UTF-8
          locale --all-locales
      - uses: actions/configure-pages@v5
      - run: python -m src.csl_sanitizer
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/
